spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intern?characterEncoding=UTF-8
    username: root
    password: 1234
  data:
    mongodb:
      uri: mongodb://localhost:27017/intern
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  batch:
    job:
      enabled: false