create table creative (
    id bigint generated by default as identity,
    created_date timestamp,
    updated_date timestamp,
    exposure_end_date timestamp,
    exposure_start_date timestamp,
    price bigint,
    status integer,
    title varchar(255),
    primary key (id)
);

create table creative_count (
    id bigint generated by default as identity,
    count bigint,
    creative_id bigint,
    primary key (id)
);

create table creative_image (
    id bigint generated by default as identity,
    extension varchar(255),
    name varchar(255),
    size bigint,
    creative_id bigint,
    primary key (id)
);

alter table creative_count
    add constraint FKg77exxj646r9ga20rgi9baod2
    foreign key (creative_id)
    references creative;

alter table creative_image
    add constraint FKs5dq7803f72wm181b2aglps3b
    foreign key (creative_id)
    references creative;